# Generated by Django 3.2.10 on 2022-08-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='api_img',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('width', models.CharField(max_length=50)),
                ('height', models.CharField(max_length=50)),
                ('images', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
